config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #home page    controller: page / template: home.html.erb
#   get("/", to: "page#home")
  #or can simply use:
  root "pages#home"
  
  get("/about",to: "pages#about")
  
  # resourses: automatically sets the new/edit/destroy path for me !!!!
  #article routes 
  resources :articles
  
  #user routes
  get("/signup", to: "users#new")
  resources :users, except: [:new]
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to:"sessions#destroy"
  
  resources :categories, except: [:destroy]
  
  
  
end

app/models/article.rb
class Article < ActiveRecord::Base
    
    #belongs_to associations must use the singular term. 
    #If you used the pluralized form in the above example for the author association
    #in the Book model, you would be told that there was an 
    #"uninitialized constant Book::Authors". 
    #This is because Rails automatically infers the class name from the association name.
    #If the association name is wrongly pluralized, 
    #then the inferred class will be wrongly pluralized too.
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories 
    
    validates :title, presence: true, length: {maximum: 50, minimum: 3}
    validates :description, presence: true, length: {minimum: 10}
    #enforce that the article must have an user ID
    validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    #set the value the @article
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    #add a middleware here to restrict from the controller and not only from the UI
    before_action :require_user, except: [:index, :show]
    
    def new
        @article = Article.new
    end
    
    def create
        # i could do like this, but not safe either practical - solution: define a function
        # @article = Article.new(title: params[:article][:title], description: params["article"]["description"])
        @article = Article.new(article_params) # it autom adds the category and saves everything
        @article.user = current_user
        if @article.save
            flash[:success] = "Article successfuly created!"
            redirect_to article_path(@article)
        else    
            render "/articles/new"    
        end
    end
    
    def show
        # @article = Article.find(params[:id])
    end
    
    def edit
    #   @article = Article.find(params[:id]) 
    end
    
    def update
        # @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = "Article successfuly updated!" 
            redirect_to article_path(@article)
        else
            render "edit"
        end
    end
    
    def index
        # @articles = Article.all #grabs all article from the db, return an array
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
       
    def destroy
        # @article = Article.find(params[:id])
        if @article.destroy
            flash[:info] = "Article successfuly deleted!"
            redirect_to articles_path
        end
    end
    
############################ FUNCTION DEFINITION ############################### 
    def article_params
      params.require(:article).permit(:title,:description,:category_ids=>[]) #indicates that will come as array
    end
    
    def set_article
      return @article = Article.find(params[:id])
    end
end

app/views/articles/_form.html.erb
<!--form partial!!-->
<br>
<div class="container middle">

    <%= render "shared/errors", obj: @article%>

    <%= form_for @article do |f|%>
        <div class="form-group">
            <label><%= f.label :title, "Title" %></label>
            <%= f.text_field :title, class:"form-control", placeholder:"Article title" %>
        </div>
        <div class="form-group">
            <label><%= f.label :description, "Description" %></label>
            <%= f.text_area :description, class:"form-control",rows:10, placeholder: "Description" %>
        </div>
        <div class="row">
            <!--undestand method as argument-->
            <!--object, method, collection, value_method, text_method, options = {}, html_options = {}-->
            <!--The :value_method and :text_method parameters are methods to be called on each member of collection. 
            <!--The return values are used as the value attribute and contents of each check box tag, respectively. -->
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
                <div class="col-xs-3 form-group">
                    <%= b.label(class:"checkbox-inline") {b.check_box + b.text} %>
                </div>
            <%end%>
        </div>
        <div class="form-group">
            <%= f.submit class:"btn btn-success" %> <!-- automatically POST request -->
        </div>
        <%= link_to "Back", :back %>
    
    <% end %>
</div>

app/views/articles/_show_articles.html.erb
<br>
<% obj.each do |art|%>
      <div class="well well-sm">
         <div class="row">
            <div class="col-md-12">
               <p class="article-title"><%= link_to art.title, "/articles/#{art.id}"%></p>
               <p class="article-body"><%= truncate(art.description, length: 150)%></p>
               <div>
                  <small>
                     Created by: <%=art.user.username%>  <!-- :DDDD -->
                     <%= time_ago_in_words(art.created_at)%> ago | 
                     Last update: <%= time_ago_in_words(art.updated_at)%> ago
                  </small>
               </div>
            </div>
         </div>
         <% if art.categories.any? %>
            <br>
            <span><strong>Categories: </strong></span>
            <% art.categories.each do |category| %>
               <span class="label label-info">
                  <%= link_to category.name, 
                              category_path(category), 
                              style:"color:white;font-size:12px;"%>&nbsp;</span>
            <% end %>
            
         <%end%>
         <% if logged_in? && (art.user == current_user || current_user.admin?) %> <!-- current_user returns a User obj -->
            <div class="row">
               <div class="col-md-12">
                  <hr style="margin-bottom:10px; margin-top:10px;">
                  <%= link_to "Edit", edit_article_path(art), class:"btn btn-xs btn-primary"%>
                  <%= link_to "Delete",article_path(art), 
                                       method: :delete, 
                                       data: {confirm: "Confirm delete?"}, 
                                       class:"btn btn-xs btn-danger"%>
               </div>
            </div>
         <%end%>
      </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container middle">
   <h2>Edit - <%=@article.title%></h2>
</div>

<%= render "form" %><!--dont need to specify the directory once its in the same folder-->

app/views/articles/index.html.erb
<h1 align="center">All articles</h1>

<%= render "show_articles", obj: @articles%>

<!--show up only if there are enough articles to next page-->
<div align="center"><%= will_paginate @articles%></div>

app/views/articles/new.html.erb
<div class="container middle">
   <h2>New article:</h2>
</div>

<%= render "form" %><!--dont need to specify the directory once its in the same folder-->

app/views/articles/show.html.erb
<h1 align="center"><%=@article.title%></h1>
<hr class="style">
<p><%=simple_format(@article.description)%></p>
<p>
   <strong>Author: 
      <em><%=link_to @article.user.username, user_path(@article.user)%></em>
   </strong>
</p>
<% if @article.categories.any? %>
   <span><strong>Categories: </strong></span>
   <% @article.categories.each do |category|%>
      <span class="label label-info">
         <%= link_to category.name, 
                     category_path(category), 
                     style:"color:white;font-size:12px;"%>&nbsp;</span>
   <%end%>
<%end%>

<hr class="style">
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
   <div>
      <%= link_to "Edit", edit_article_path(@article), class:"btn btn-sm btn-primary"%>
      <%= link_to "Delete",article_path(@article), method: :delete, data: {confirm: "Confirm delete?"}, class:"btn btn-sm btn-danger"%>
   </div>
<%end%>
<br/>
<p><%= link_to "Back to articles", articles_path%></p>