config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #home page    controller: page / template: home.html.erb
#   get("/", to: "page#home")
  #or can simply use:
  root "pages#home"
  
  get("/about",to: "pages#about")
  
  # resourses: automatically sets the new/edit/destroy path for me !!!!
  #article routes 
  resources :articles
  
  #user routes
  get("/signup", to: "users#new")
  resources :users, except: [:new]
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to:"sessions#destroy"
  
  resources :categories, except: [:destroy]
  
  
  
end

app/views/layouts/_footer.html.erb
<footer>
   <div class="container">
      <hr>
      <span>Made by &copy; Chih</span>
      <a href="/about" class="pull-right">About</a>
   </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
   <div class='alert alert-<%="#{name}"%>'>
   <a href="#" class="close" data-dismiss="alert">&times;</a> <!-- add the x to the alert message -->
     <p><%= msg %></p>
   </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="brand" class="navbar-brand" href="/"><i class="fa fa-commenting" aria-hidden="true"></i> BloG</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if !logged_in? %>
          <li><a href="/articles">Articles<span class="sr-only">(current)</span></a></li>
          <li><a href="/users">Users</a></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/articles">Articles</a></li>
              <li><a href="/articles/new">Create a new article </a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/users">View all users</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/categories">View all categories</a></li>
            <% if logged_in? && current_user.admin? %>
              <li><a href="/categories/new">Create a new category <i class="fa fa-plus-circle" aria-hidden="true"></i></a></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <% Category.all.each do |cat|%>
              <li><a href="/categories/<%=cat.id%>"><%=cat.name%></a></li>
            <%end%>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
          <li><%= link_to raw("Register <i class='fa fa-user-plus' aria-hidden='true'></i>"),signup_path%></li>
          <li><a href="/login">Log in <i class="fa fa-sign-in" aria-hidden="true"></i></a></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= "Admin " if current_user.admin? %><%= current_user.username %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View my profile", user_path(current_user) %></li>
              <li><a href="/users/<%=current_user.id%>/edit">Edit my profile</a></li>
              <% if !current_user.admin?%>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Delete my account", 
                                "/users/#{current_user.id}" , 
                                method: :delete, 
                                data: {confirm: "Are you sure you want to delete the account?"} %>
                </li>
              <% end %>
            </ul>
          </li>
          <li>
            <%= link_to raw("Sign out <i class='fa fa-sign-out' aria-hidden='true'></i>"), logout_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <div class="container middle">
      <%= render "layouts/messages"%>
      <%= yield %> <!-- this refers to all the page templates -->
      <%= debug(params) if Rails.env.development?%>
    </div>
    <%= render "layouts/footer"%>
    
    
  </body>
</html>